### ISSUE TITLE
Abstraction Layers for building Messages payload

### ISSUE THREAD

**Issue by Maclenn77** [alexrudall/anthropic#23]
**Is your feature request related to a problem? Please describe.**

Building the payload for messages it's prone to errors and it gets more complex when you need to add images. I was thinking if a layer that handle that for you would be useful for this library or it's something that it should be left to other projects such as boxcars.

**Describe the solution you'd like**

Abstraction layers that handle building a messages array for the payload.

**Describe alternatives you've considered**
A class that handles the building of the message's payload, something a Anthropic::MessagesBuilder, that it would build the payload according to what is required (User message without previous messages, chat history, user message with an image or multiple images, etc.)

A class for Messages (it could be Anthropic::Message with attributes ´role´ (´user´ or ´assistant´) and ´content´. Content can be text or image. 

It could also be a small gem just for this one. I'm also wondering if it would be just okay use other gems such boxcars or lanchainrb, or it would be a nice addition to this gem. 

**Additional context**

**Comment by alexrudall** [comment]
@Maclenn77 - could be nice - I think a separate gem might make sense.
