### ISSUE TITLE
400 Bad Request Faraday error on a small variation of the sample code in README

### ISSUE THREAD

**Issue by itsmeritesh** [alexrudall/anthropic#24]
**Describe the bug**
400 Bad Request - Faraday Error 

**To Reproduce**

Running my function in a rails app. 

Function takes a string argument OCR-text, which is scans of bio text books and written material.

**Expected behavior**
 Should return a structured JSON of the organisms mentioned in the extracted_text. 

**CODE BLOCK**

```
def extract_bio(ocr_text) 
@prompt = "Analyze the user provided text, and identify any references to wildlife. For all matching organisms include the name, biological name, description among other attributes, return results in the declared JSON format. [only elaborate where you can cite a verified source, return Nil otherwise"
@output_json_format = '[{"Name": "Name of the referenced animal or species",  
 "description": "brief description of the organism", "article-date": "date of publishing in datetime format","location": "full address, or lat long"}]'
claude = Anthropic::Client.new  
  
response = claude.messages(  
  parameters: {  
    model: "claude-3-haiku-20240307",  
    system: @prompt,  
    messages: [  
      {"role": "user", "content": ocr_text},  
      { "role": "assistant", "content": @output_json_format }  
    ],  
    max_tokens: 1000  
  }  
)
puts response
end

```

**Desktop (please complete the following information):**
 - OS: [e.g. MacOS]
 - Browser [e.g. chrome]

**Additional context**
I'm declaring Anthropic::Client in an initializer.rb file.

**Comment by itsmeritesh** [comment]
I'd posted this on the discord yesterday. This is a duplicate.

**Comment by Maclenn77** [comment]
> 3. If I'm trying to orchestrate a few such calls using Ruby, is there a framework that helps, similar to long chain, that's recommended for use in Ruby?

@itsmeritesh did you mean "langchain" ? Check [langchainrb](https://github.com/patterns-ai-core/langchainrb) or [boxcars](https://github.com/BoxcarsAI/boxcars)

**Comment by gerrywastaken** [comment]
```ruby
def break_the_rule_of_putting_in_more_effort_than_the_question_asker
  response = claude.messages(
    parameters: {
      model: "claude-3-haiku-20240307",
      system: https://github.com/prompt,
      messages: [
        {"role": "user", "content": ocr_text},
        { "role": "assistant", "content": @output_json_format }
      ],
      max_tokens: 1000
    }
  )
  puts response
rescue
  $!.response_body
end
```

**Comment by itsmeritesh** [comment]
Thank you!

**Comment by alexrudall** [comment]
@itsmeritesh -- is this one resolved now? Thanks!

**Comment by gerrywastaken** [comment]
@alexrudall it is, it just wasn't obvious that the call was throwing an exception that could be caught to get the message body:

Maybe some info here would help:
https://github.com/alexrudall/anthropic?tab=readme-ov-file#messages

But either way, the problem was that the message was in the response_body of the exception and you probably won't see that unless you have a rescue around the call to `.messages`

**Comment by alexrudall** [comment]
@gerrywastaken got it -thank you! I'll add an issue to add verbose logging as I think that would be helpful.
