### ISSUE TITLE
Add Streaming!

### ISSUE THREAD

**Issue by alexrudall** [alexrudall/anthropic#7]
- Need streaming to make this library more useful in prod!

**Comment by mybuddyandrew** [comment]
Did you add this?

**Comment by alexrudall** [comment]
> Did you add this?

Not yet! Ya need it?

**Comment by gus-bn** [comment]
+1, please add streaming :)

**Comment by alexrudall** [comment]
Thanks @swombat - released in [v0.3.0](https://github.com/alexrudall/anthropic/releases/tag/v0.3.0)!
