### ISSUE TITLE
Support for messages endpoint

### ISSUE THREAD

**Issue by duncantmiller** [alexrudall/anthropic#9]
Since the complete endpoint is now [depricated](https://docs.anthropic.com/claude/reference/complete_post) and Anthropic is recommending migrating to messages, are there any plans to add support for the new [messages endpoint](https://docs.anthropic.com/claude/reference/messages_post)?

**Comment by alexrudall** [comment]
@duncantmiller - I would welcome a PR on this!

**Comment by alexrudall** [comment]
@duncantmiller could you review this? https://github.com/alexrudall/anthropic/pull/10

**Comment by svs** [comment]
I also took a shot. Slightly slower and hopefully less dirty :-)

https://github.com/alexrudall/anthropic/pull/11

**Comment by jtoy** [comment]
can we merge this please

**Comment by alexrudall** [comment]
Released in [v0.2](https://github.com/alexrudall/anthropic/releases/tag/v0.2.0) - thanks all for your contributions!
